language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
before_install:
  - sudo apt-get update
  - sudo apt-get install binutils libproj-dev gdal-bin
  - sudo apt install libsqlite3-mod-spatialite 
script:
  - python manage.py test PlacesRemember