language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_install:
  - sudo apt-get update
  - sudo apt-get install binutils libproj-dev gdal-bin
  - sudo apt install libsqlite3-mod-spatialite 
script:
  - python manage.py test PlacesRemember
  - coverage run --source=config/PlacesRemember config/manage.py test PlacesRemember
after_success: coveralls